import { roboto } from '@/ui/fonts'
import NavBar from '@/components/NavBar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <NavBar/>
        {children}
      </body>
    </html>
  )
}
